name: Update Sponsors

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: # æ‰‹å‹•å®Ÿè¡Œã‚‚å¯èƒ½

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: GitHub Sponsors README Action
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSOR_TOKEN }}
          file: README.md

      # Deploy the changes back to the main branch of the repository
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Typically this should be the name of the base branch, in many cases this is 'main'.
          branch: main
          # As we're deploying changes to our markdown files, this needs to be . to push the root directory back to the repository.
          folder: '.'
