name: Update Lean
on:
  schedule:
    # 毎日実行
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update_lean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      # panic! を Ubuntu 上で評価するとバックトレースが表示されてしまう問題の修正
      - name: set environment variable
        run: echo "LEAN_BACKTRACE=0" >> $GITHUB_ENV
      - name: Update Lean project
        uses: leanprover-community/lean-update@main
        with:
          update_if_modified: lean-toolchain
          build_args: "--log-level=warning --fail-level=warning"
